# docker-compose
#   crear un contenedor con la app
#   crear un contenedor con un servicio MongoDB (database)
#   crear un contenedor con un servicio Redis (memcach)
#
# app debe poder conectarse con database y memcach


version: '3.8'

services:
  capp:
    container_name: tecgurus_app
    image: tecgurus/devops:ejemplo-001
    resources:
      cpu: 1
      memory: 1024K 
    port:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - /home/guest/Projects/DevOps_desde_cero-Mar2025/exercises/devops_app_repo:/container/app
    networks:
      - tecgurus

  cdatabase:
    container_name: tecgurus_database
    image: mongo:latest
    port:
      - "27017:27017"
    volumes:
      - /home/guest/Projects/DevOps_desde_cero-Mar2025/exercises/mongodb:/data/db
    networks:
      - tecgurus

  cmemcach:
    container_name: tecgurus_memcach
    image: redis:latest
    port:
      - "6379:6379"
    networks:
      - tecgurus

networks:
  tecgurus:
    driver: bridge

